// Import Google fonts from Next.js built-in font system
import { Geist, Geist_Mono } from "next/font/google";

// Import global styles
import "./globals.css";

// Import Bootstrap CSS for styling
import 'bootstrap/dist/css/bootstrap.min.css';

// Import our Client Component wrapper for SessionProvider
import { Providers } from "./providers"; // 👈 important

// Configure custom Google fonts
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Default metadata for your site (used by Next.js for <head>)
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// ✅ Only ONE RootLayout is allowed
// This wraps your entire app with <SessionProvider> (for login state)
// and applies your Google fonts + Bootstrap
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* Apply Google fonts via CSS variables */}
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {/* Use our Providers wrapper (client component) */}
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
